extends: ['eslint:recommended', 'plugin:react/recommended']

plugins: ['babel', 'react', 'mocha']

parser: 'babel-eslint'

env:
  es6: true
  browser: true
  node: true

parserOptions:
  ecmaFeatures:
    modules: true
    jsx: true

rules:
  quotes: ['error', 'single']
  semi: ['error', 'never']
  generator-star-spacing: ['error']
  object-shorthand: ['error']
  arrow-parens: ['error']
  babel/new-cap: ['error', {capIsNewExceptions: ['Immutable.Map', 'Immutable.List', 'Immutable.Set', 'Immutable.OrderedSet', 'Immutable.OrderedMap']}]
  mocha/no-exclusive-tests: 'error'
