extends: ['eslint:recommended', 'plugin:react/recommended']

plugins: ['babel', 'react', 'mocha']

parser: 'babel-eslint'

env:
  es6: true
  browser: true
  node: true

parserOptions:
  ecmaVersion: 8
  ecmaFeatures:
    modules: true
    jsx: true

rules:
  quotes: ['error', 'single']
  semi: ['error', 'never']
  generator-star-spacing: ['error']
  object-shorthand: ['error']
  arrow-parens: ['error']
  babel/new-cap: ['error', {capIsNewExceptions: ['Map', 'List', 'Set', 'OrderedSet', 'OrderedMap', 'Record']}]
  mocha/no-exclusive-tests: 'error'
