extends: eslint:recommended

plugins: ['react']

env:
  es6: true
  jest: true
  jasmine: true
  browser: true
  node: true

ecmaFeatures:
  modules: true
  jsx: true

rules:
  quotes: [2, 'single']
  semi: [2, 'never']
