extends: stylelint-config-standard

plugins:
  - stylelint-order
  - stylelint-scss
rules:
  string-quotes: single
  font-family-name-quotes: always-where-required
  function-url-quotes: always
  at-rule-no-unknown: null
  scss/at-rule-no-unknown: true
  scss/at-function-pattern: ^_{0,1}[a-z\-]+$
  scss/at-mixin-pattern: ^_{0,1}[a-z\-]+$
  scss/dollar-variable-pattern: ^_{0,1}[a-z\-]+$
  scss/percent-placeholder-pattern: ^_{0,1}[a-z\-]+$
  scss/no-duplicate-dollar-variables: true
  scss/double-slash-comment-whitespace-inside: always
  scss/dollar-variable-colon-space-before: never
  scss/dollar-variable-colon-space-after: always
  order/properties-alphabetical-order: true
