extends: stylelint-config-standard

plugins:
  - stylelint-order
rules:
  string-quotes: single
  font-family-name-quotes: always-where-required
  function-url-quotes: always
  at-rule-no-unknown:
    - true
    - ignoreAtRules:
       - extend
       - include
       - mixin
       - content
       - each
       - if
  order/properties-alphabetical-order: true
