module.exports = {
  AppInit: 'app-init',
  RestoreConfiguration: 'restore-configuration',
  TrayAdd: 'tray-add',
  TrayUpdate: 'tray-update',
  TrayRemove: 'tray-remove',
  PasswordEncrypted: 'password-encrypted',
  ProjectsFetching: 'projects-fetching',
  ProjectsFetched: 'projects-fetched',
  ProjectsFetchError: 'projects-fetch-error',
  ProjectSelected: 'project-selected',
  ProjectUnselected: 'project-unselected',
  InterestingProjects: 'interesting-projects',
  InterestingProjectsError: 'interesting-projects-error',
  MessageAdd: 'message-add',
  MessageInvalidInput: 'message-invalid-input',
  MessageRemove: 'message-removed',
  ImportingData: 'importing-data',
  ImportError: 'import-error',
  ExportData: 'export-data',
  ConfigurationLoaded: 'configuration-loaded',
  BrokenBuildTimersChanged: 'broken-build-timers-changed',
  Notification: 'notification',
  NotificationDismiss: 'notification-dismiss',
  KeyboardShortcuts: 'keyboard-shortcuts'
}
