name: Nevergreen CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    env:
      CI: true

    name: Build
    runs-on: ubuntu-18.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup JDK
        uses: actions/setup-java@v1
        with:
          java-version: 13

      - name: Install clojure tools-deps
        uses: DeLaGuardo/setup-clojure@master
        with:
          tools-deps: latest
          lein: latest

      - name: Clojure - dependencies
        run: lein deps

      - name: Clojure - tests
        run: |
          lein coverage
          lein lint

      - name: Setup Node
        uses: actions/setup-node@v1
        with:
          node-version: 15.3.0

      - name: node - dependencies
        run: npm ci

      - name: node - tests
        run: |
          npm run check-types
          npm run test:coverage
          npm run lint

      - name: Package
        run: |
          npm run build:prod
          lein uberjar

      - name: Run Cypress
        uses: cypress-io/github-action@v1
        env:
          CYPRESS_BASE_URL: "http://localhost:5000"
          CYPRESS_TRAY_URL: "https://raw.githubusercontent.com/build-canaries/nevergreen/master/cctray_xml_feed_mock/resources/cctray.xml"
          CYPRESS_TRAY_URL_TOKEN: ""
          CYPRESS_TRAY_TOKEN: ""
          CYPRESS_TRAY_USERNAME: ""
          CYPRESS_TRAY_PASSWORD: ""
        with:
          start: java -jar target/nevergreen-standalone.jar
          wait-on: http://localhost:5000

      - name: Store Cypress artifacts
        uses: actions/upload-artifact@v1
        if: always()
        with:
          name: cypress-video
          path: target/test-reports/journey/journey.test.js.mp4

      - name: Store Nevergreen artifact
        uses: actions/upload-artifact@v1
        with:
          name: nevergreen-jar
          path: target/nevergreen-standalone.jar


