name: Nevergreen CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    env:
      CI: true

    name: Build
    runs-on: ubuntu-18.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup JDK
        uses: actions/setup-java@v1
        with:
          java-version: 11


      - name: Install clojure tools-deps
        uses: DeLaGuardo/setup-clojure@master
        with:
          tools-deps: latest
          lein: latest
     
      - name: Run Clojure tests
        run: |
          lein deps
          lein test
          lein lint
          lein clean
          lein uberjar
        
      - name: Setup Node
        uses: actions/setup-node@v1
        with:
          node-version: 12

      - name: Run Node tests
        run: |
          npm ci
          npm run check-types
          npm run build:prod
          npm test
          npm run lint
        