name: Node.js and Clojure CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    
    - name: Use Java 11
    - uses: actions/setup-java@v1
      with:
        java-version: 11 # The JDK version to make available on the path.
    - uses: DeLaGuardo/setup-clojure@2.0
      with:
        tools-deps: '1.10.1.469'
    - name: Install dependencies
      run: lein deps
    - name: Run tests
      run: lein test
    
    - name: Use Node.js 12
      uses: actions/setup-node@v1
      with:
        node-version: 12
    - run: npm ci
    - run: npm run build --if-present
    - run: npm test
      env:
        CI: true